name: Validation
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with Go
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Composer
        run: composer validate
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.8'
      - name: Display the Go version
        run: go version
      - name: Download YAML translation utilities
        run: |
          go get github.com/sijad/yaml-translation-utils/same-yaml
          go get github.com/sijad/yaml-translation-utils/yamllinter
      - name: Compare YAML files
        run: bash .github/scripts/identical.sh
      - name: Lint YAML files
        run: bash .github/scripts/linter.sh
